### ISSUE TITLE
Smart contract tutorial

### ISSUE THREAD

**Issue by jhodgdev** [mlabs-haskell/apropos-tx#47] opened 2022-04-28 10:35 UTC
As discussed, it'd be useful to have a dummy smart contract e.g. an auction that we could then write example test cases for. This could be accompanied by a series of tutorial documents explaining the how/what/where/why.

**Comment by AriFordsham** [comment] 2022-11-15 13:27
Duplicate of https://github.com/mlabs-haskell/apropos/issues/66

**Closed as completed by AriFordsham** 2022-11-15 13:27 UTC
Labels: documentation, help wanted
